'use strict';
let token='',project=null,dirty=false,projects=[];
const $=id=>document.getElementById(id);
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);}
async function request(path,body,raw=false){const options=body===undefined?{}:{method:'POST',headers:{'X-LF-Token':token,'Content-Type':raw?'application/octet-stream':'application/json'},body:raw?body:JSON.stringify(body)};const r=await fetch(path,options);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
function changed(){dirty=true;$('saved').textContent='Unsaved changes';}
function renderProject(p){project=p;dirty=false;localStorage.setItem('lectureforge-project',p.id);$('home').hidden=true;$('project').hidden=false;$('project-name').textContent=p.name;$('source').textContent=`${p.source.original_name} · ${p.source.slide_count} slides · source SHA-256 ${p.source.sha256}`;$('preset-info').textContent=p.preset.name;$('saved').textContent='Saved';$('slides').replaceChildren();
 for(const s of p.slides){const row=document.createElement('article');row.className='slide'+(s.enabled?'':' disabled');row.dataset.number=s.number;const heading=document.createElement('h3');const label=document.createElement('label');const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=s.enabled;enabled.className='enabled';label.append(enabled,document.createTextNode(`Slide ${s.number} — ${s.title}`));heading.append(label);const scriptLabel=document.createElement('label');scriptLabel.textContent='Narration script';const script=document.createElement('textarea');script.rows=5;script.value=s.script;script.className='script';scriptLabel.append(script);const pauseLabel=document.createElement('label');pauseLabel.textContent='Silence after speech (seconds)';const pause=document.createElement('input');pause.type='number';pause.min='0';pause.max='120';pause.step='0.001';pause.value=s.post_speech_silence_seconds;pause.className='pause';pauseLabel.append(pause);row.append(heading,scriptLabel,pauseLabel);row.addEventListener('input',()=>{row.classList.toggle('disabled',!enabled.checked);changed();});$('slides').append(row);}}
async function openProject(id){renderProject(await request('/api/project?id='+encodeURIComponent(id)));message('Project loaded.');}
async function refresh(){const d=await request('/api/bootstrap');token=d.token;projects=d.projects;$('root').textContent='Projects: '+d.root;$('preset').replaceChildren();for(const p of d.presets){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;$('preset').append(o);}$('project-list').replaceChildren();for(const p of projects){const b=document.createElement('button');b.className='secondary';b.textContent=`${p.name} · ${p.slides} slides`;b.onclick=()=>action(()=>openProject(p.id));$('project-list').append(b);}if(!projects.length)$('project-list').textContent='No saved lectures yet.';}
async function action(fn){try{await fn();}catch(e){message(e.message,true);}}
async function save(){if(!project||!dirty)return;const slides=[...$('slides').children].map(r=>({number:Number(r.dataset.number),enabled:r.querySelector('.enabled').checked,script:r.querySelector('.script').value,post_speech_silence_seconds:Number(r.querySelector('.pause').value)}));renderProject(await request('/api/save?id='+project.id,{version:project.version,slides}));message('Changes saved.');}
$('new').onclick=()=>{$('new-form').hidden=false;$('projects').hidden=true;$('name').focus();};$('open').onclick=()=>action(async()=>{await refresh();$('projects').hidden=false;$('new-form').hidden=true;});
$('new-form').onsubmit=e=>{e.preventDefault();action(async()=>{const file=$('pptx').files[0];if(!file||!file.name.toLowerCase().endsWith('.pptx'))throw Error('Choose a .pptx file.');const button=e.target.querySelector('button');button.disabled=true;message('Copying and inspecting PowerPoint…');try{const q=new URLSearchParams({name:$('name').value,filename:file.name,preset:$('preset').value});renderProject(await request('/api/new?'+q,await file.arrayBuffer(),true));message('Lecture created. Import or edit its slide scripts.');}finally{button.disabled=false;}});};
$('save').onclick=()=>action(save);$('back').onclick=()=>action(async()=>{await save();project=null;localStorage.removeItem('lectureforge-project');$('project').hidden=true;$('home').hidden=false;await refresh();});
$('script-file').onchange=()=>action(async()=>{$('script-import').value=await $('script-file').files[0].text();});
$('import').onclick=()=>action(async()=>{await save();renderProject(await request('/api/save?id='+project.id,{version:project.version,script_import:$('script-import').value}));message('Scripts imported and saved.');});
for(const [id,value] of [['enable-all',true],['disable-all',false]])$(id).onclick=()=>{for(const row of $('slides').children){row.querySelector('.enabled').checked=value;row.classList.toggle('disabled',!value);}changed();};
$('folder').onclick=()=>action(()=>request('/api/folder?id='+project.id,{}));
$('stop').onclick=()=>action(async()=>{await save();await request('/api/stop',{});dirty=false;document.querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=true);message('LectureForge stopped. Your projects are saved. Run Start-LectureForge.ps1 to return.');});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
action(async()=>{await refresh();const id=localStorage.getItem('lectureforge-project');if(id&&projects.some(p=>p.id===id))await openProject(id);});
